name: Deploy WP - Renan Buitrago [Staging]
on:
  push:
    branches:
      - buitragorestg
      
jobs:
  deploy:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync
        uses: Burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --filter=". ./.rsync-filter"
          path: cms/          
          remote_host: 35.236.219.140
          remote_port: 15051
          remote_path: /www/renanbuitragocms_618/public/wp-content
          remote_user: renanbuitragocms
          remote_key: ${{ secrets.KINSTA_SSH_DEPLOY_PRIVATE_KEY }}