name: Deploy WP - Yarimar Ruiz - Staging
on:
  push:
    branches:
      - yarimarruizstg
jobs:
  deploy:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync
        uses: Burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --filter=". ./.rsync-filter"
          path: cms/          
          remote_host: 35.236.219.140
          remote_port: 60501
          remote_path: /www/yarimarruizcms_365/public/wp-content
          remote_user: yarimarruizcms
          remote_key: ${{ secrets.KINSTA_SSH_DEPLOY_PRIVATE_KEY }}